### PR TITLE
Added translations for Galician, Basque and Catalan

### PR DESCRIPTION
**Pull request by ACMCMC**
#7

### CODE REVIEW

**Comment by essana3** [comment]
@ACMCMC make sure you add the calling code as well and we added more countries as well.
Pull the latest version from the master branch to see the changes and change your files accordingly

**Comment by ACMCMC** [comment]
Done! :)

**Comment by essana3** [comment]
Not yet, you didn't adapt your countries to the new model.

**Comment by ACMCMC** [comment]
I had misread your comment, sorry! I believe everything should be OK now :)

**Pull request merged**
